<a href="https://colab.research.google.com/github/electrolabopen/redesgan/blob/main/pytorch.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Tensores en Pytorch#

In [2]:
import torch

In [3]:
A = torch.randn(4,4,4)

In [4]:
A.size()

torch.Size([4, 4, 4])

In [5]:
len(A.size())

3

In [6]:
A[0]

tensor([[ 0.3474, -0.3178, -0.0059,  0.7113],
        [ 0.8271, -0.4409,  0.8878, -2.2628],
        [ 0.2030, -1.2079,  0.5862,  1.0913],
        [ 0.6011, -1.0319, -0.6854, -1.4643]])

In [7]:
A[0, 0:4,0]

tensor([0.3474, 0.8271, 0.2030, 0.6011])

#Enviar a CPU o a GPU#

In [8]:
A.device

device(type='cpu')

#Ver disponibilidad de GPU#

In [9]:
torch.cuda.is_available()

True

In [10]:
hallaca = torch.device('cuda') if torch.cuda.is_available() else ('cpu')

In [11]:
z = torch.randn(3,5)

In [12]:
z

tensor([[ 0.2763, -1.4244,  1.5097, -1.5118,  0.5102],
        [-0.5803,  0.1511,  0.7074,  0.5297, -0.5245],
        [ 0.0401, -0.9405, -0.5267,  1.0047, -1.1912]])

In [14]:
y = torch.ones_like(z, device=hallaca)

In [15]:
y

tensor([[1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.],
        [1., 1., 1., 1., 1.]], device='cuda:0')

In [16]:
z = z.to(hallaca)

In [17]:
z + y

tensor([[ 1.2763, -0.4244,  2.5097, -0.5118,  1.5102],
        [ 0.4197,  1.1511,  1.7074,  1.5297,  0.4755],
        [ 1.0401,  0.0595,  0.4733,  2.0047, -0.1912]], device='cuda:0')

#Crear capas de Redes Neuronales#

In [19]:
import torch
import torch.nn as nn

linear = nn.Linear(in_features=1000, out_features=10)


#Convolucion#

In [22]:
conv = nn.Conv2d(in_channels=3, out_channels=9, kernel_size=3, stride=1,padding=1)

In [23]:
z = torch.randn(1000)

In [24]:
salida = linear(z)
salida

tensor([ 0.6094,  0.3741, -0.6662, -0.6926,  0.1446, -0.5171, -0.4289,  0.7449,
        -0.6249, -0.9685], grad_fn=<AddBackward0>)

#Funciones de activacion#

In [25]:
import torch.nn.functional as F 

#La relu todos los numeros positivos los deja pasar, los numero negativos los aplana a cero#

In [26]:
F.relu(salida)

tensor([0.6094, 0.3741, 0.0000, 0.0000, 0.1446, 0.0000, 0.0000, 0.7449, 0.0000,
        0.0000], grad_fn=<ReluBackward0>)

#Crear la red neuronal#

In [28]:
class Net(nn.Module):
  
    def __int__(self,num_channels):

      super(Net,self).__int__()
      self.num_channels = num_channels

      self.conv1 = Conv2d(3, self.num_channels,kernel_size=3, stride=1, padding=1)


      self.conv2 = Conv2d(self.num_channels, self.num_channels*2, kernel_size=3, stride=1, padding=1)


      self.conv3 = Conv2d(self.num_channels*2, self.num_channels*4,kernel_size=3, stride=1, padding=1)

      self.fc1 = nn.Linear(4*self.num_channels*8*8,100)

      self.fc2 = nn.Linear(100,6)

    def forward(self,z):

      #convulucionales
      z = self.conv1(z)       # num_channels * 64*64

      z = F.max_pool2d(z,2)   #num_channels * 32*32

      z = F.relu(z)           #num_channels * 32*32

      z = self.conv2(z)        # 32*32

      z= F.max_pool2d(z,2)      #16*16

      z= F.relu(z)             # 16*16

      z = self.conv3(z)        # 16*16

      z= F.max_pool2d(z,2)     # 8*8

      z= F.relu(z)             # 8*8

      #Flatten

      z = z.view(-1, 4*self.num_channels*8*8)


      #Fully conected

      z = self.fc1(z)

      z = F.relu(z)

      z = self.fc2(z)

      z = F.log_softmax(x,dim=1)

      return z